mikebrady/shairport-sync

audio_pulse.c
Sometimes, when shairport is running for a while on pulseaudio, it randomly disconnects.
This results in the console flooding with this message:
audio_pulse.c: pa_simple_write() failed: Connection terminated
This PR corrects this by catching the error and reconnecting to pulse.
(The error happens on my debian jessie, pulseaudio 5.0-13 amd64)
=> Pulseaudio: reconnect automatically

rtsp.c
If the `ANNOUNCE` and/or `SETUP` method fails, the `play_lock` mutex is never unlocked, thus blocking other clients from connecting. 
This patch unlocks `play_lock` if an error occurs in either `ANNOUNCE` or `SETUP`. Actually, one might consider not locking `play_lock` until a successful `SETUP` (or even `RECORD`). Another option would be to force-close the connection, if either `ANNOUNCE` or `SETUP` fail. 
The motivation for this patch was the following: PulseAudio's `module-zeroconf-discover` automatically loads `module-raop-sink`, which in turn sends both `ANNOUNCE` and `SETUP` requests. `SETUP` fails because no ports are listed in the header's `Transport` section, but PulseAudio does not close the connecting in face of the non-200 response code, thus `play_lock` stays locked forever, …
=> Fix deadlocks in RTSP code

Makefile.am, RELEASENOTES.md, audio.c, audio.h, audio_alsa.c, audio_ao.c, audio_dummy.c, audio_pipe.c, audio_pulse.c, audio_sndio.c, audio_stdout.c, common.c, common.h, mdns.c, mdns.h, mdns_avahi.c, mdns_dns_sd.c, mdns_external.c, mdns_tinysvcmdns.c, player.c, player.h, rtp.c, rtp.h, rtsp.c, rtsp.h, scripts/shairport-sync.conf, shairport.c, tinysvcmdns.c, tinysvcmdns.h
A lot of under-the-hood changes in this branch to be merged back to the main development branch:
* A revised, simplified and clarified way of regulating the flow of packets through to the output device, leading to limited support for different audio back ends.
* A new audio back end – `audio_stdout`
* Support for the `audio_pipe` and `audio_dummy` back ends.
* Limited defacto support continues for unsynchronised `pulseaudio` output.
* New configuration file options for setting backend buffer sizes and synchronisation offsets for each type of supported back end.
=> Flow control improvements and limited support for different backends.

RELEASENOTES.md, configure.ac, shairport.c
Update release notes and bump version number.
=> Portnumbers

README.md, RELEASENOTES.md, audio_alsa.c, common.h, configure.ac, player.c, rtp.c, rtsp.c, scripts/shairport-sync.conf, shairport.c
Shaiport Sync can use source-supplied latency setting, hurray!
=> Dynamic latency

.gitignore, configure.ac, scripts/shairport-sync.service.in
#139 was recently closed but I think this does what was discussed in there and it seems pretty useful for packaging in general.
=> Substitute $PREFIX in the systemd unit file (Fixes #139).

Makefile.am, configure.ac
As recomended by debain maintainers and
http://www.freedesktop.org/software/systemd/man/daemon.html#Installing%20Systemd%20Service%20Files
=> Correct method to determine systemd unit path

README.md
Add a note to `README.md` that a version for Debian is now available.
=> README: add a note about Debian

common.h, player.c, shairport.c
HI Mike - trying again with a new pull request against the development branch to add the "mono" option.
=> Added option for mono output

UPDATING.md
`$git pull` hurts my eyes...
`$ git pull` is much better :)
=> Add spaces after `$`

configure.ac, player.c
Handle short packets such as sent by the HTC 10 – experimental and needs regression testing.
=> Short packets

rtp.c
=> constant 0x100000000 should be 0x100000000LL to avoid warning

rtsp.c
=> Fix ClientIP info in metadata [development branch; attempt #2]

rtp.c
clock_drift could be left uninitialized. because of the re-declaration.
=> Small problem with clock_drift.

common.c, player.c, rtsp.c
During this year I've developed a new audio backend for shairport-sync that implements a simple DLNA (Digital Living Network Alliance) media server and media controller. With that software I can tell iTunes to play music on my stereo receiver, which supports DLNA but no Airport.
When I tested that software, I found a couple of issues, some of which are in the original source base from your repository. With this pull request I'd like to share my findings with you and propose fixes for them.
Is it okay for you to have one pull request for five small, but unrelated fixes at once, or do you prefer separate pull requests? And what about commit comments? I've added comprehensive, but not always short, explanations for all issues to the respective commit comments. I hope, they're enough to …
=> Some issues found during the development of a DLNA backend

scripts/shairport-sync.conf
https://github.com/mikebrady/shairport-sync/pull/751 fix on development branch
=> (development) normalize whitespaces in scripts/shairport-sync.conf

Makefile.am, player.c
Stop duplicate gdbus codegen calls during parallel makes
Remove a few unused functions in player.c
=> Tidy up a few things

mqtt.c
=> Small logic fix

scripts/shairport-sync.conf, shairport.c
PR for #854 
1. update example shairport-sync.conf file
2. update config file mqtt port parsing
Signed-off-by: David Crook <idcrook@users.noreply.github.com>
=> mqtt port config changes

TROUBLESHOOTING.md
=> For issue #937

README.md
Add install guide for gentoo user
=> add gentoo install guide

CAR INSTALL.md
I added a chapter about disabling unnecessary services in order to decrease boot-time. And I added a short tip about read-only mode.
=> Added chapters about optimising boot time and about read-only filesystem

docker/Dockerfile, docker/README.md, docker/classic/Dockerfile
https://github.com/mikebrady/shairport-sync-docker/pull/19
=> Add avahi-tools and update readme

BUILD.md
Don't need to checkout development branch.
=> Don't need to checkout development branch.

configure.ac, rtsp.c
Fixes https://github.com/mikebrady/shairport-sync/issues/1674.
=> Fix compilation with `libplist` 2.3.0.

.github/workflows/check_ap2_systemd_basic.yml, .github/workflows/check_ap2_systemd_full.yml, .github/workflows/check_ap2_systemd_full_build_folder.yml, .github/workflows/check_ap2_systemv_full.yml, .github/workflows/check_classic_mac_basic.yml, .github/workflows/check_classic_systemd_basic.yml, .github/workflows/check_classic_systemd_full.yml, .github/workflows/docker-build-on-push_and_pull_request.yaml
With this PR your workflows (tests) are also triggered on pull requests. So the code is checked already before it reaches `development` branch.
=> Run workflows on pull requests

audio_jack.c
Adds a missing format string argument.
=> Add missing format string argument

AIRPLAY2.md, README.md, rtsp.c
- clarify root privilege requirements
- Sprinkle OpenBSD news in README.md
- fix [-Wunused-variable] for keep* variables
=> OpenBSD doc nits

.gitignore, mqtt.c
Trying again from this attempt:
https://github.com/mikebrady/shairport-sync/pull/2000
=> Add mqtt disconnect command
