mikebrady/shairport-sync

- mdns_dns_sd.c
implicit declaration of free due to missing include for stdlib.h [on linux/amd64]
const/const char mixing
> Fix compiler warnings

- player.c
- rtsp.c
shairport-sync crashes on musl libc when accessing the `statistics` array in `player_thread_func()`. This array is quite large (60128 bytes) and altogether the data for this thread exceed the the default stack size on musl libc of 80k [1].
Safe and portable programs should not depend upon the default stack limit, but instead, explicitly allocate enough stack for each thread by using the pthread_attr_setstacksize routine [2].
So, lets set the stack size for the `player_thread` to 128k. A follow-up patch may set the stack sizes for the other threads, too. The difficulty here is to decide how much memory to allocate for the stack.
[1]
http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc#Thread_stack_size
[2]
https://computing.llnl.gov/tutorials/pthreads/#Stack
> Fix segfault with musl libc

- Makefile.am
- configure.ac
- scripts/shairport-sync.service
- shairport-sync.spec
I'm not entirely sure how you want to handle the difference between system V init scripts and systemd.  The way the --with and --without options are currently you could end up with both.
> minor changes to support fedora and systemd

- Makefile.am
There looks to be a missing `$DESTDIR` in the systemv init script part of the makefile. 
I noticed this when trying to [create a Debian package](https://github.com/kingosticks/shairport-sync/tree/debian) and had tried to use a `dh_installinit --onlyscripts` rule. 
The call to `update-rc.d` then also gave problems.  Would it be reasonable to only perform that command when $(DESTDIR) is unset? Something like:
```
[ -n $(DESTDIR) ] || update-rc.d shairport-sync defaults 90 10
```
> Use DESTDIR when checking systemv script exists

- shairport.c
You couldn't set a custom pid directory because the USE_CUSTOM_LOCAL_STATE_DIR macro was still used. Therefore the daemon_pid_file_proc would never point to the function locating the custom pid directory.
> No custom PID directory because USE_CUSTOM_LOCAL_STATE_DIR macro still used.

- configure.ac
configure will pass any CPPFLAGS and LDFLAGS supplied to it, it helps with OS X builds where dns_sd is system library
> Use AC_SEARCH_LIBS for dns_sd in configure.ac

- RELEASENOTES.md
- audio.h
- audio_alsa.c
- audio_ao.c
- audio_dummy.c
- audio_pipe.c
- audio_pulse.c
- audio_sndio.c
- audio_stdout.c
- common.h
- player.c
Allow the volume range to be extended using a combination of software and hardware attenuation, where necessary. (Some cheap DACs have a very small attenuation range.)
Also, handle a frame buffer overflow slightly better.
> Volume extend

- .gitignore
The generated makefiles in the man/ subdirectory are not currently ignored by git. This upsets git buildpackage (yes, I am still working on this!!).
> Fix git not ignoring generated files in man/

- rtsp.c
Different processor targets may have different word alignment restrictions. Typically, a two or four byte integer should start on a four-byte address in order to be fetched correctly over a bus. An access of a misaligned memory element may cause a bus error.
Therefore, we need to adjust the contents of a message by copying it into a new location, before interpreting it.
Reference:
http://www.csc.kth.se/utbildning/kth/kurser/DD2490/ipro1-10/homeworks/homework_4b_alignment.html
Fixes: https://github.com/mikebrady/shairport-sync/issues/174, https://github.com/mikebrady/shairport-sync/issues/171
> Fix data allignment issue

- rtsp.c
Some server simply ignore the md field from the TXT record. If The config says 'please, do not include any cover art', we are polite and do not write them to the pipe.
> Ignore received picture item if include_covert_art is set to no

- .gitignore
- configure.ac
- scripts/shairport-sync.in
Simplifies building packages for older distros, my VCR is still running 12.04
PS. i'm also producing an ubuntu ppa for the development releases now https://launchpad.net/~dantheperson/+archive/ubuntu/shairport-sync-devel
> User $PREFIX in the init file

- configure.ac
- man/Makefile.am
- man/shairport-sync.7
- man/shairport-sync.7.xml
- man/shairport-sync.html
A pair of commits that:
* Fix a few typos in the manpage XML source
* Update the built manpage and HTML file
* Use `xmltoman` to rebuild the manpage and HTML docs when it's available
> Manpage fixes

- common.h
- rtp.c
- shairport.c
Add in a Linux-only ability to favour a "public" IPv6 source address when connecting to a distant IPv6 port. This is to help with systems that use IPv6 privacy extensions.
Also, restore the ability to compile in FreeBSD
> Public ipv6

- audio_alsa.c
- rtsp.c
- rtsp.h
- shairport.c
Reduce the number of mutex locks in play, and simplify how signalling occurs between threads.
> Prune locks

- configure.ac
Otherwise build fails for cross-compilation. See http://autobuild.buildroot.net/results/682/6821605cf12e1a5393c29b30baf00cb0f1e1a451/build-end.log
> Fix static linking with openssl and alsa

- README.md
- audio.h
- audio_alsa.c
- common.c
- common.h
- configure.ac
- player.c
- rtp.c
- rtsp.c
- scripts/shairport-sync.conf
- shairport.c
Detect and handle when the packet buffers are exhausted. (!)
Modify the way `audio_alsa` gets delay information from the `alsa` subsystem.
Gracefully handle occasions when the delay information is unavailable or the delay returns a negative result.
Add an option to turn off synchronisation (this is probably temporary).
Add two options for setting `alsa` period size and `alsa` buffer size – advanced usage only.
Start to tidy up arithmetic errors due to sloppy observance of type mixing and promotion rules.
Add some `alsa` information to debug info.
Tidy up some debug messages; drop the priority of some and raise others.
> Modify delay check

- rtsp.c
Initialise the mutex and two condition variables inside pc_queue during pc_queue_init().
Fixes #262.
> Mutex and Condition Variable Initialisation

- README.md
- common.h
- mdns_tinysvcmdns.c
- rtsp.c
- scripts/shairport-sync.conf
- shairport.c
Hi Mike - got another pull request for you.
I have never managed to get the "metadata over pipe" working reliably: if my client doesn't connect at the right time, or if it drops the connection, I don't seem to get anything and have no way to recover. Worse, connecting to a named FIFO when shairport-sync is not running will block, which is a problem in environments like Java: it will hang the current thread, with no way to recover cleanly.
So this pull request adds an option to broadcast metadata to a UDP socket address.
The advantages here are the listeners to this socket can come and go without any need to coordinate with the server. Also, you can use a multicast address to broadcast metadata to multiple cilents (tested the theory successfully), or a remote address to send metadata over …
> Metadata over UDP

- audio_alsa.c
The ALSA softvol plugin allows the user to add a new volume control and control the sound volume by software. This is necessary if the sound card cannot control the volume by hardware.
An example configuration in the `~/.asoundrc` file might look like this:
```
pcm.softvol {
type softvol
slave {
pcm "hw:0"
}
control {
name "Master"
card 0
}
min_dB -57.2
max_dB -6.2
}
ctl.softvol {
type hw
card 0
}
```
The corresponding entries in the shairport-sync would be:
```
alsa =
{
output_device = "softvol";
mixer_control_name = "Master";
}
```
Please check the [ALSA documentation](http://alsa.opensrc.org/Softvol) and the [ALSA PCM library reference](http://www.alsa-project.org/alsa-doc/alsa-lib/pcm_plugins.html).
If shairport-syncs alsa backend does not have success in getting the dB volume …
> Add support for ALSA softvol plugin

- common.c
This fixes calculation of the scaled attenuation if `max_dB` is different from
zero.
Closes: https://github.com/mikebrady/shairport-sync/issues/290
> Fix vol2attn

- player.c
Example output with synchronization enabled:
```
sync error in frames,net correction in ppm,corrections in ppm,total packets,missing packets,late packets,too late packets,resend requests,min DAC queue size,min buffer occupancy,max buffer occupancy
28.1,0.0,0.0,3758,0,1,0,1,4350,207,238
30.0,0.0,0.0,7516,0,2,0,2,5646,210,235
36.0,0.0,0.0,11274,0,4,0,4,5702,200,235
159.9,0.0,0.0,15032,0,7,0,7,5770,207,235
167.8,0.0,0.0,18790,0,8,0,8,5930,203,234
79.4,0.0,0.0,22548,0,9,0,9,5818,206,235
82.8,0.0,0.0,26306,0,10,0,10,5726,206,235
53.0,0.0,0.0,30064,0,13,0,13,5482,208,235
203.6,0.0,0.0,33822,0,16,0,16,5874,205,235
133.4,0.0,0.0,37580,0,19,0,19,5758,219,235
151.4,0.0,0.0,41338,0,23,0,23,5818,211,235
262.5,0.0,0.0,45096,0,24,0,24,5946,217,235
176.5,0.0,0.0,48854,0,28,0,28,5978,215,235 …
```
> Make statistics output more parsable

- common.c
- shairport.c
Commit f36352dc4ece27fda24ef736183b8ff5729b8c96 introduced the parameter `pipe_timeout` for the metadata config. If shairport-sync is now configured without metadata support, the build fails with:
```
shairport.c: In function ‘main’:
shairport.c:766:9: error: ‘shairport_cfg {aka struct <anonymous>}’ has no member named ‘metadata_pipe_timeout’
config.metadata_pipe_timeout = 5000; //milliseconds
common.c: In function ‘non_blocking_write’:
common.c:525:30: error: ‘shairport_cfg {aka struct <anonymous>}’ has no member named ‘metadata_pipe_timeout’
rc = poll(ufds, 1, config.metadata_pipe_timeout);
```
Fix this by guarding the affected code by `CONFIG_METADATA`.
> Fix build without metadata support

- scripts/shairport-sync.conf
Just a nit, but I tried using UDP metadata and it didn't work - kept getting port 0.  I tracked it down to the example config file using a string, but the code requires a number.
So, this changes the sample config file to reflect that.
> In config file, metadata socket_port needs to be a number, not a string

- audio_alsa.c
Use alsa direct access (mmap) feature to improve performance if mmap is supported.
For some embedded systems such as LinkIt 7688 running OpenWrt, alsa always underruns without  mmap.
> use alsa mmap feature if supported

- rtp.c
On OS X `getaddrinfo` does not set the scope_id for ipv6 link-local addresses so we set it manually instead.
This fixes errors such as `Error sendto-ing to timing socket: No route to host` on OS X.
> Ensure scope_id is set correctly for ipv6 timing and control sockets

- mdns_avahi.c
If the avahi daemon is not up when shairport-sync is started or the avahi daemon restarts while shairport-sync is running makes shairport-sync to fail. Improve this by:
1. Add an option to the avahi client to not fail if the daemon is not up yet.
2. Add an avahi client error handler which tries to reconnect to the avahi daemon.
> Add avahi client error handling

- rtsp.c
Metadata was previously reporting server ip as client ip "ssnc-clip".
Fixed by:
- providing remote_ip data instead of ip data for metadata in rtsp.c
- continuing export of ip data under "ssnc-svip" metadata tag
> Fix ClientIP info in metadata

- Makefile.am
- audio.c
- audio_soundio.c
- configure.ac
- shairport.c
Support for C library for cross-platform real-time audio input and output
http://libsound.io/
https://github.com/andrewrk/libsoundio
Everything works, please try, need suggestion about settings for software latency.
> Initial support for libsoundio

- .gitignore
- FFTConvolver/AudioFFT.cpp
- FFTConvolver/AudioFFT.h
- FFTConvolver/FFTConvolver.cpp
- FFTConvolver/FFTConvolver.h
- FFTConvolver/Utilities.cpp
- FFTConvolver/Utilities.h
- FFTConvolver/convolver.cpp
- FFTConvolver/convolver.h
- Makefile.am
- common.c
- common.h
- configure.ac
- loudness.c
- loudness.h
- player.c
- scripts/shairport-sync.conf
- shairport.c
Hello Mike,
Following "issue" #480, here the code that integrates both filters. It works great on my Raspberry Pi.
What would be even better would be a way to activate/deactivate them on the fly, so we can hear the before/after. Any suggestion on how I could interact live with an instance of shairport-sync? I was thinking about using a simple read from stdin, or ncurses to make it a bit more sexy, or even some simple http frontend like https://github.com/cesanta/mongoose, but that might be overkill.
The convolution part, using C++, must be activated with `--with-convolution` during `./configure`.
I put some documentation in `script/shairport-sync.conf`.
> 2 audio filters added, a volume-dependent-loudness and a convolution filter

- audio_sndio.c
- common.c
- configure.ac
- scripts/shairport-sync.conf
The title says it all :wink:. I'm hoping this can be merged.  Seems to work well together with my lowly iPad 1.
The development branch doesn't currently build on FreeBSD, so this includes a small fix:  FreeBSD doesn't have `ETIME` so I replaced it with `ETIMEDOUT`. Nothing checks for `ETIME` so I hope this is fine.
Thank you!
> Rewrite and unbreak sndio backend

- audio_pulse.c
Desired buffer length was not specified in seconds for Pulseaudio, which broke playback completely.
> Fixed desired buffer length for Pulseaudio

- rtsp.c
Sending metadata over UDP currently suffers from two main issues:
- send buffer is left to system default, and consequently packets can be lost as Airplay clients send a lot of metadata;
- some metadata (typically the cover art) cannot be sent within a single IPv4 UDP packet because they are too large.
These commits fix both issues by setting larger send buffer of 4MB and chunking any metadata with a new sub-protocol ("ssnc", "chnk", packet_ix, packet_counts, packet_tag, packet_type, chunked_data)
> Fix issues with sending metadata over UDP socket

- shairport.c
fix "metadata" typo in verbose output
> Fix typo in shairport-sync.c

- audio_alsa.c
- common.c
- common.h
- shairport.c
refs GH-452
this will enable me to multiplex a small number of USB audio cards (say 2 or 3) into a much larger matrix, and still have AirPlay advertise each zone individually (as well as virtual airplay zones activating multiple physical zones, if I desire)
> read stdout from the on-start command to choose ALSA output device

- shairport-sync.spec
Using the --with-systemd option will cause make install to
issue groupadd and useradd commands which will fail in
mock build environments like koji and copr.
> don't use --with-systemd configure option

- README.md
README.md previously did not include instructions for compiling the convolution filter. I’ve updated it to include the `--with-convolution` flag in `./configure`, and to include the requirement for libsndfile.
> Update README.md for convolution filter

- audio_alsa.c
There is a bug in the hardware volume control that affects some devices. (Those devices do not allow the volume to be set in dB directly and instead rely on conversions to their native volume scale. One example is the Softvol plugin in ALSA.)
Shairport-sync fails silently when presented with such a device when hardware volume control is enabled: the volume events have no effect.
I fixed this by adding two missing lines of code to the init() function in audio_alsa.c.
> Fix volume bug

- common.c
- common.h
- mdns_external.c
- player.c
- rtp.c
- rtsp.c
- shairport.c
I've got one other issue besides those in pull request #611, but this one is more complicated and more debatable, so I think it's better to open a separate pull request for it.
Many threads have got a main loop that checks some exit variable in the loop condition, e.g. `conn->please_stop`, `conn->timing_sender_stop` or `conn->stop`. To stop a thread, another thread sets that exit variable, sends a SIGUSR1 to that thread to get it out of blocking calls like `read()`, `write()` or `select()`, and finally joins it.
There is a hidden race condition though, a lost signal condition, which actually hit me several times: The signal wakes up the target thread only if it is actually blocked right now. If the target thread is currently executing some code outside the above mentioned system calls, it …
> Fixed race condition when stopping other threads with SIGUSR1

- audio_alsa.c
Somewhere in the version 3.x the softvol plugin got broken as the volume
change is not applied anymore. Turned out for the softvol plugin no
`volume()` and `parameters()` are defined.
> Fix usage of ALSA softvol plugin

- tinysvcmdns.c
This patch incorporates upstream's fixes for a remotely exploitable buffer overflow bug in the bundled `tinysvcmdns` library. The following upstream commits are included:
https://bitbucket.org/geekman/tinysvcmdns/commits/48c73fbb36b7a5584b00538d89c89dd8b15ab2a7
https://bitbucket.org/geekman/tinysvcmdns/commits/29ea1b9fca94dc42d16109e050d2967231b1e341
The changes have been incorporated preserving local changes such as the check for `malloc()` returning `NULL`.
Reported against `shairport-sync` in Ubuntu Launchpad:
https://bugs.launchpad.net/ubuntu/+source/shairport-sync/+bug/1729668
This commit closes GitHub issue #619.
This is a cherry-pick onto the `master` branch of the same commit from the `development` branch. Please prepare a stable 3.1.x release with this fix for users who don't …
> Fix CVE-2017-12087 in bundled tinysvcmdns (master branch)

- tinysvcmdns.c
This patch incorporates upstream's fixes for a remotely exploitable buffer overflow bug in the bundled `tinysvcmdns` library. The following upstream commits are included:
https://bitbucket.org/geekman/tinysvcmdns/commits/48c73fbb36b7a5584b00538d89c89dd8b15ab2a7
https://bitbucket.org/geekman/tinysvcmdns/commits/29ea1b9fca94dc42d16109e050d2967231b1e341
The changes have been incorporated preserving local changes such as the check for `malloc()` returning `NULL`.
Reported against `shairport-sync` in Ubuntu Launchpad:
https://bugs.launchpad.net/ubuntu/+source/shairport-sync/+bug/1729668
This commit closes GitHub issue #619.
> Fix CVE-2017-12087 in bundled tinysvcmdns (development branch)

- Makefile.am
- README.md
- common.c
- common.h
- configure.ac
- mqtt.c
- mqtt.h
- rtsp.c
- scripts/shairport-sync.conf
- shairport.c
Hi there,
Because MQTT is a fairly often used protocol in FOSS home-automation projects (as well as in commercial ones), and shairport-sync is often used in these setups, I've added client-support for this protocol in shairport-sync.
It's either possible to publish a subset of metadata, or the raw metadata, as this may be way simpler for many people than implementing an FIFO/UDP reader- & parser.
Additionally, it's possible to directly send DACP commands over mqtt (`/InstanceName/remote`) which uses the `send_simple_dacp_command` function.
There may be few issues with this implementation (e.g. it relies on the traditional `metadata` to be enabled), but I think it may be a starting point.
It'd be nice if you could have a look at the modified `configure.ac` file, as I'm not that familiar …
> Added MQTT support (Metadata & RC)

- README.md
- audio_pa.c
- common.h
I believe the title explains the contribution quite well. 
I recently wanted to switch from using Shairport Sync on all Raspberries around my house to using it on one server and distributing the audio using PulseAudio's sinks and server-client connections. To be able to do that, I had to add a configuration option to Shairport Sync that would allow me to specify a sink that I want to push audio to.
> Add configuration option to specify PulseAudio output sink

- scripts/shairport-sync.conf
This inconsistency int tab/spaces was pretty annoying while editing shairport-sync.conf :)
Or is there a reason behind it?
> normalize whitespaces in scripts/shairport-sync.conf

- audio_alsa.c
- audio_pa.c
- common.h
- configure.ac
- player.c
- player.h
- rtp.c
- rtp.h
- rtsp.c
The system by which timestamp intervals has been calculated was fragile and has been replaced. It was fragile because, while an occasional simple network error could be dealt with correctly, a sequence of serious network errors could render its fundamental assumptions invalid and completely break it -- on occasions, in fact, Shairport Sync got so confused that it would programmatically quit!
So, these changes will not magically fix problems due to a faulty network, but they should make Shairport Sync more robust in dealing with errors.
There is a possibility that some errors may be reintroduced, particularly in the area of flushing behaviour at the start of a new play session that quickly follows a previous one, or indeed elsewhere.
> Revamped timestamp calculation

- .gitignore
- Makefile.am
- audio_alsa.c
- configure.ac
- shairport.c
Tools associated with D-Bus automatically generate code for the `dbus` and `MPRIS` interfaces that causes compilation warnings when `-Wall` and friends are set. To avoid this, automatically generated code is compiled separately into static libraries, using standard compiler switches. The libraries are then linked to the other object files as normal.
> Separate compilation of automatically generated code

- TROUBLESHOOTING.md
The instructions for disabling the low-power/power-saving mode were for merely the onboard chip that comes with some of the latest Raspberry Pis.
This is all well and good but there are other popular Wi-Fi adapters out there as well. And their procedures are completely different.
This pull request extends the troubleshooting page with instructions for disabling low-power/power-saving mode for additional Wi-Fi chips.
> Instructions for additional Wi-Fi chips

- mdns.c
The build flags for external mDNS support broke the build on macOS.
This simply moves some code around to fix the build again.
> Fix the build on macOS

- README.md
- configure.ac
- mqtt.c
- shairport.c
The following commits fix a bug I recently discovered, where full album art was published via mqtt although being disabled. 
Additionally, some checks were added to inform the user that avahi is neccessary for some functionality in the mqtt client (#795). This also applies to some possibly wrong configurations where the underlaying metadata is not enabled. A bit of debug information may also help.
> MQTT Bug & usability improvements

- CAR INSTALL.md
- INSTALL.md
- README-DEVELOPMENT.md
- README.md
- RELEASENOTES-DEVELOPMENT.md
- RELEASENOTES.md
- TROUBLESHOOTING.md
- activity_monitor.c
- alac.h
- audio.c
- audio_alsa.c
- audio_jack.c
- audio_sndio.c
- common.h
- dbus-service.c
- man/shairport-sync.7
- man/shairport-sync.7.xml
- metadata_hub.h
- player.c
- player.h
- rtsp.c
- scripts/shairport-sync.in
- shairport-sync.spec
- shairport.c
- tinyhttp/chunk.h
- tinysvcmdns.c
Previously I have made spelling changes as caught by Debian's lintian tool, which has a short list of common misspellings that it tests for. This time I decided to run `codespell` against the source and fix all the obvious problems it came up with. It also uses a list of misspellings but it's much larger than lintian's, but also has some false positives so I went over the list by hand.
The command I used to do check the source was:
```
$ git ls-tree -rz --name-only HEAD | xargs -0 codespell -L minimise,errorstring
```
> More typo fixes across the tree

- shairport.c
By returning early (and with success) it will always be possible to get version and usage without crashing if there are errors in creation or destruction of i.e. threads.
> Early exit on version and help arguments

- rtsp.c
This fixes a possible seg. fault, when an incomplete a:fmtp parameter set is send by the requesting client (less than 12 parameter).
See also #897
> Alac a fmtp seg fault

- player.c
This PR increases the debug level of the constantly repeated resend check log message (`check start`) from `2` to `3`.
When setting `log_verbosity` to 2, the constantly repeated log message `check start` drowns out any other useful messages. However, the log should still remain human-readable on this "medium" setting.
<p align="center">
<i>Screencast</i><br>
</p>
- Changed `debug()` call:
https://github.com/sidneys/shairport-sync/blob/hotfix/log-verbosity-level/player.c#L631
> [FIX] Fix verbosity level of player.c debug message

- audio_jack.c
- common.h
- scripts/shairport-sync.conf
First attempt at adding soxr resampling to the jack audio output, I thought I would share it already.
Some notes:
> Jack output add soxr resampling

- audio_pa.c
- common.h
- scripts/shairport-sync.conf
Add "server" entry to pa config section, allowing to connect to a remote or a local system
pulseaudio instance instead of letting pulseaudio choose.
> Allow to specify pulseaudio server instead of using default one.

- player.c
Use signed integers when calculating backend latency adjustment to prevent truncation of negative offsets.
> Use signed integers to prevent truncation of negative backend offset.

- activity_monitor.c
Found that MQTT activity_start: abeg and activity_end: aend topics where never being published. 
background:
Immediately after a play session started a play_end: pend topic was sent.  Also after the activity_timout a duplicate play_end was received.
Fix:
This commit fixes those bugs by correctly the metadata codes from "pend" to the correct "abeg" and "aend"
This was tested in my docker development setup on a RPI 3. it worked well
> Updated activity_monitor.c - metadata publishing wrong codes

- shairport.c
Just a couple of typo fixes that were automatically detected during my latest Debian packaging.
> Fix typos of "daemon"

- pair_ap/README.md
- pair_ap/pair.h
- pair_ap/pair_homekit.c
- rtsp.c
- shairport.c
Hi @mikebrady here is a PR that updates pair_ap to a version where the pair_list response is fixed (hopefully), and which adds SPS support for the pair-add/list/remove and configure requests so that pairing with the Home app is possible.
The pairings are only persisted in memory. Perhaps that will turn out to be inadequate, we will see.
You may also want to add freeing of the pairings on server termination.
> Home app pairing (support for pair-add etc)

- tinysvcmdns.c
Fixes issues when using tinysvcmdns: Service not visible any more after some time.
(Similiar to #1098)
> Fix tinysvcmdns: rr_data_len goes beyond packet buffer

- Makefile.am
- audio.c
- audio_pw.c
- configure.ac
Hey! It's me again.
I've been wanting to work with pipewire more so I decided to write an audio output for it!
This audio backend takes a lot of design decisions from my pulseaudio rewrite in #1175 
Pipewire and pulseaudio share a lot of similarities and you will see that in the design. There are some major differences in the way data is queued though. You will see that a buffer needs to be dequeued (acquired) from pipewire, data can then be copied into the buffer, then the buffer can be queued again. If a buffer isn't returned when dequeuing we wait for the pipewire mainthread to signal that we can process more data and try to dequeue a buffer again.
This actually works quite well as pipewire let's you throw data at it quickly the blocking/waiting that happens is very minimal.
A lot of …
> pipewire: add initial support

- configure.ac
Find sndfile through pkg-config to retrieve sndfile dependencies such as flac and avoid the following static build failure:
```
/tmp/instance-3/output-1/host/lib/gcc/xtensa-buildroot-linux-uclibc/10.3.0/../../../../xtensa-buildroot-linux-uclibc/bin/ld: /tmp/instance-3/output-1/host/bin/../xtensa-buildroot-linux-uclibc/sysroot/usr/lib/libsndfile.a(libsndfile_la-flac.o): in function `flac_byterate':
flac.c:(.text+0xfc): undefined reference to `FLAC__StreamDecoderErrorStatusString'
```
Fixes:
- http://autobuild.buildroot.org/results/92ed30a6855ca11800b779718822bcba4a69c9a3
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: find sndfile through pkg-config

- rtp.c
Hi @mikebrady , thank you for your effort on making shairport-sync work with Airplay2.
I was trying to get this working on another flavour of the Pi (RockPi-E, https://wiki.radxa.com/RockpiE), which supports Ubuntu 18.
This had the unfortunate problem where shairport-sync fails with the message "Can't find an AAC decoder!". Upon digging, the issue appears to be that Ubuntu 18's default apt repository has FFmpeg 3.4, not FFmpeg 4.x.
After some more digging, I found adding this line resolves the issue. My understanding is that this shouldn't introduce any bad side effects when built using FFmpeg 4.x.
Would appreciate your thoughts on whether this is a reasonable addition, or if you are aware of a more elegant way of handling this.
Thanks
> small change to fix codec loading for ubuntu-18/ffmpeg-3.4

- configure.ac
This fixes #1345 by checking for the `libplist` library both under the name `libplist` and `libplist-2.0` using the fallback strategy [as described in the autotools docs](https://autotools.io/pkgconfig/pkg_check_modules.html).
Since we now try both names, we no longer need the FreeBSD/Linux check.
> Try finding libplist as libplist-2.0 on Linux too

- audio_sndio.c
Ending a RTSP session while running on OpenBSD using sndio backend causes the
following crash:
#0  thrkill ()
#1  0x000005208224403e in _libc_abort
#2  0x00000520821b77be in _rthread_mutex_trylock
#3  _rthread_mutex_timedlock
#4  0x0000051e0d54e2c0 in stop ()
#5  0x0000051e0d544e85 in player_thread_cleanup_handler
#6  0x0000052082243126 in _libc_pthread_exit
#7  0x000005209a158700 in sigthr_handler
#8  <signal handler called>
#9  _thread_sys_poll ()
#10 0x000005208223533e in _libc_poll_cancel
#11 0x00000520df54c9a0 in sio_psleep
#12 0x00000520df54cc1f in sio_write
#13 0x0000051e0d54e27a in play
#14 0x0000051e0d547fc0 in player_thread_func
#15 0x000005209a158cc1 in _rthread_start
#16 0x000005208223565a in __tfork_thread
The player thread is blocking inside sio_write() -> poll(2) while the …
> avoid recursive mutex acquisition in sndio backend

- .github/workflows/docker-build-on-push.yaml
- .github/workflows/docker-build-on-tag.yaml
- docker/README.md
- docker/airplay1/Dockerfile
- docker/airplay1/README.md
- docker/airplay1/start.sh
- docker/docker-compose.yaml
Automatically builds a docker image based on master (AP1 only) on push to branch or on git tag.
`unstable-master` is created on a commit to the branch.
`latest` and `[TAG]` are created on tag to main branch.
Means `shairport-sync-docker` repo can be depreciated.
> Automated docker tagging.

- MQTT.md
- mqtt.c
document some more of the fields that can come through, and add a few more "parsed" messages:
* active_remote_id
* dacp_id
* server_ip
> some MQTT metadata improvements

- docker/Dockerfile
- docker/etc/services.d/01-dbus-daemon/finish
- docker/etc/services.d/01-dbus-daemon/run
Noticed an issue when dbus needed to restart where the dbus.pid still existed so it failed.
> Fix for dbus restart.

- audio_pw.c
Hello again! I've had a little spare time so I wanted to contribute again.
This updates the pipewire sink:
- Adds protection for the mainloop locking via `pthread_setcancelstate` when appropriate.
- Adds protection against deadlocks by using the timed wait method `pw_thread_loop_timed_wait_full`
I'm not sure if you would rather me call `die` if the timeout is reached. I'm not sure in an instance when this may happen.
> Pipewire: updates

- .gitignore
- Makefile.am
This allow building in a separate build directory (rather than in the source directory)
```
mkdir -p build && cd build
autoreconf -ivf ..
../configure --with-avahi --with-pw --without-pa --with-ssl=openssl --with-mpris-interface --with-dbus-interface --with-systemd --prefix=/usr
make $(nproc)
DESTDIR=install make install
```
I've also changed from `cp` to using `install` this is used anyways by autotools. Hopefully there is no change in behaviour.
without the build fix
```
$ make 
gdbus-codegen --interface-prefix org.gnome --generate-c-code dbus-interface org.gnome.ShairportSync.xml
Traceback (most recent call last):
File "/usr/bin/gdbus-codegen", line 55, in <module>
sys.exit(codegen_main.codegen_main())
File "/usr/share/glib-2.0/codegen/codegen_main.py", line 412, in codegen_main
with …
```
> Makefile.am: allow building and installing from a separate build directory

- MQTT.md
The old way of configuring mqtt entities is not supported anymore since `v2022.12`
> Migrate to new HA mqtt configuration

- MQTT.md
The payload for `active start` & `active end` is not empty but `--`. Fix the examples accordingly.
> Fix MQTT active start / active end examples

- docker/Dockerfile
- docker/classic/Dockerfile
- docker/etc/s6-overlay/s6-rc.d/04-nqptp/dependencies
Fixes https://github.com/mikebrady/shairport-sync/issues/1677
On slower hardware startup (and readiness) of the `s6` services (`dbus` and `avahi`) can exceed the default `s6` timeout of 5000ms. 
Adding `S6_CMD_WAIT_FOR_SERVICES=1` and `S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0` should fix the issue. For the flags see https://github.com/just-containers/s6-overlay#customizing-s6-overlay-behaviour
Additionally, `nqptp` does not depend on `avahi` and `dbus` so it's started right away.
> Fix s6-timeout issues on slower devices

- audio_ao.c
The `libao` library provides the `matrix` option to allow rearranging output channel ordering, but this only works when the application specifies the input channel ordering.
Before: `shairport-sync -o ao -- -o matrix=R,L` does nothing
After: `shairport-sync -o ao -- -o matrix=R,L` swaps L and R channels
Multichannel is still an issue, e.g. `shairport-sync -o ao -- -o matrix=X,X,L,R` still does nothing, but AFAICT this is a problem with `libao` and not `shairport-sync`.
> Fix libao matrix option by specifying channel ordering

- metadata_hub.c
- rtsp.c
When building against recent `openssl` versions (>3.0) (e.g. used by `alpine:3.17`) a lot of deprecation warnings are generated. Reason is that `openssl` removed some low-levl API functions, e.g. `MD5XXX()` or changed the function mappings, e.g. `RSAXXX()`, `AESXXX()`. For more details see [here](https://www.openssl.org/docs/man3.0/man7/migration_guide.html).
This PR fixes the `MD5XX()` related warnings. 
```
../rtsp.c:4889:3: warning: 'MD5_Init' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
#31 1.227  4889 |   MD5_Init(&ctx);
#31 1.227       |   ^~~~~~~~
#31 1.227 In file included from ../rtsp.c:58:
#31 1.227 /usr/include/openssl/md5.h:49:27: note: declared here
#31 1.227    49 | OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
#31 1.227       | …
```
> Fix some openssl 3.0 deprecation warnings

- configure.ac
Resolves #1705. Tested against https://github.com/NixOS/nixpkgs/pull/242350.
> configure.ac: check $AR for ar to use

- common.c
- common.h
- dbus-service.c
- player.c
- scripts/shairport-sync.conf
- shairport.c
Although I'm not an expert, to my ears, this logarithmic mode of volume control does a better job of making the volume percentage match the perceived volume level. That is, with logarithmic mode, 50% volume sounds half as loud as 100% volume. And 25% volume sounds a quarter as loud as 100% volume, etc. 
Dealing with airplay protocol, we have a volume between [-30, 0]. So we want -15 to sound half as loud as 0. And we want -22.5 to sound a quarter as loud as 0. Etc.
I found this page helpful for my understanding: http://www.sengpielaudio.com/calculator-levelchange.htm
FWIW I use the builtin raspberry pi soundcard. I'm not sure if perceptual loudness maps differently when using a different soundcard.
Also, no worries if you don't want to merge additional volume_control_profiles. I could …
> Add new "dasl_tapered" volume control profile

- Makefile.am
Mostly to help with packaging in NixOS.
In NixOS, we set `--prefix=/nix/store/xxxxxx/`. However, we also have to use `--without-configfiles`, lest the Makefile attempts to install the config files and friends to `/etc` (which is a complete no-go).
Specifying `DESTDIR=/nix/store/xxxxxx/` when using `--prefix=/nix/store/xxxxxx/` causes the config files to be put in the right place, but the binaries will be at `$DESTDIR/$PREFIX` (in this case `/nix/store/xxxxxx/nix/store/xxxxxx`).
This PR adds a separate `install-config-files` Makefile target that installs the config files and dbus policies to DESTDIR=, regardless of whether --with{,out}-configfiles is specified. This target exists unconditionally.
To keep the existing `make install` behaviour, `install-exec-hook` is changed to depend on …
> Makefile.am: allow manually installing config files

- ptp-utilities.c
nqptp.c listens on "localhost", but shairport-sync connectes to the wildcard
address 0/0.  This apparently works on Linux and FreeBSD, but OpenBSD fails:
```
$ ktrace shairport-sync -v -u
[...]
0.000038288 "ptp-utilities.c:243" *fatal error: error sending timing_peer_list to NQPTP
0.000021868 "shairport.c:1728" emergency exit
$ kdump
[...]
2319 shairport-sync STRU  struct sockaddr { AF_INET, 0.0.0.0:9000 }
2319 shairport-sync RET   sendto -1 errno 51 Network is unreachable
[...]
```
Resolve and connect to "localhost" just like NQPTP does, resulting in
127.0.0.1 or ::1 as socket addresses.
This is required to run when configured `--with-airplay-2`.
Tested on OpenBSD/amd64 7.4-current with shairport-sync 2.4.3 and nqptp
1.2.5-dev cfa8315 (plus OpenBSD fixes).
I expect Linux and FreeBSD to …
> Connect to NQPTP control socket on localhost

- definitions.h
- rtsp.c
A system-wide sysctl(2) net.inet.tcp.keepidle exists, but there is no
setsockopt(2) equivalent.
> No per-socket TCP keepidle on OpenBSD

- Makefile.am
- docker/Dockerfile
- docker/classic/Dockerfile
- man/Makefile
- man/shairport-sync.1
- man/shairport-sync.1.xml
- shairport-sync.spec
From mandoc man(1) [-s] section:
```
1         General commands (tools and utilities).
[...]
7         Miscellaneous information.
```
From GNU man(1) DESCRIPTION:
```
1   Executable programs or shell commands
[...]
7   Miscellaneous (including macro packages and conventions), e.g.
man(7), groff(7)
```
shairport-sync is an executable, shairport-sync(1) ought to be its documentation, not merely miscellaneous information.
OpenBSD adjusts this in its audio/shairport-sync port/package ever since.
> Move shairport-sync manual from section 7 to 1

- shairport.c
Failure to read does not exit despite
`    /* Read the file. If there is an error, report it and exit. */`
EACCES (e.g. insufficient filesystem permissions) is enough to crash on access through later `config_*()` such as those when either of either of D-Bus, MPRIS or MQTT is used.
Seen `--with-mpris-interface` and
```
$ ls -l /etc/shairport-sync.conf
-rw-r-----  1 root  _shairport  28114 Jan 25 01:53 /etc/shairport-sync.conf
$ shairport-sync
Segmentation fault (core dumped)
```
> Exit on config read error to avoid crash on EACCES

- rtsp.c
Process teardown stops all threads, thus calling pthread_cancel(3) in an
atexit(3) handler immediately before main() exits seems redundant.
On OpenBSD 7.4-current, failure to listen on the RTSP socket triggers
```
$ nc -4l 5000 &
$ nc -6l 5000 &
$ shairport-sync -c/dev/null
warning: could not establish a service on port 5000 -- program terminating. Is another instance of Shairport Sync running on this device?
Segmentation fault (core dumped)
```
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  pthread_cancel (thread=0x6207604e640) at /usr/src/lib/librthread/rthread.c:433
433             if (tib->tib_canceled == 0 && tid != 0 &&
[Current thread is 1 (process 290061)]
#0  pthread_cancel (thread=0x6207604e640) at /usr/src/lib/librthread/rthread.c:433
#1  0x0000061e5377df14 …
```
> Fix crash on double pthread_cancel(3) on exit

- shairport.c
Limit the set of system calls shairport-sync is allowed to make, most importantly fork(2)/execve(2) if and only if user defined commands are run.
OpenBSD's official audio/shairport-sync port already ships with this patch.
https://man.openbsd.org/pledge.2
> initial pledge(2) on OpenBSD

- shairport.c
OpenBSD issues syslog(3) warnings about these as they may hint at bugs:
shairport-sync: vfprintf %s NULL in "metadata socket address is "%s" port %d."
Metadata listener socket is empty by default so use the existing `strnull`.
> Avoid passing NULL pointer to printf(3) %s

- shairport.c
Configuration files may contain it, but those can be protected with filesystem permissions.
Debug log, however, may end up in syslog(3) which is usually accessible by all users on a system.
Avoid disclosing user secrets by simply not printing the password.
> Omit password in debug (syslog) output

- AIRPLAY2.md
The introduction paragraph now more clearly mentions the hard facts/requirements with "as of v4.1 and newer" and the supported devices are displayed in bullet list format for better readabilty.
> Update AIRPLAY2.md - Version introduced + Supported devices

- .github/workflows/stale.yaml
- docker/docker-compose.yaml
Added S6_KEEP_ENV to example, without it pulse connection won't happen
> Update docker compose file

- Makefile.am
- configure.ac
Useful for Yocto, for example, where groupadd or getenv is not available.
Enabled by default, to keep same behavior as before.
> Add configure option to enable/disable creation of user/group

- rtsp.c
This is a conservative change. I think I have identified an even better fix, but with more risk of regression.
Without this change (or with no general.interface configured) every address of the ShairPort Sync server seems to be advertised via PTP, including many internal Docker networks that are not reachable from elsewhere. My AirPlay sources (at least macOS 12.7.2 & iOS 17.3.1) send a lot of PTP messages to all of these addresses in parallel, most of which are rejected by my firewall.
With this change and when general.interface is set, only addresses for that interface are advertised for PTP. Even in this case my ShairPort Sync server still receives 4x seemingly duplicate streams of PTP messages to each of those addresses (static IPv4, link-local IPv6, ULA IPv6, public IPv6). The actual …
> Limit PTP addresses to configured network interface

- common.c
- player.c
- player.h
It doesn't look like anything calls `havege.h`.
Signed-off-by: Seo Suchan <tjtncks@gmail.com>
> mbedtls: add support to mbedtls3

- audio_pa.c
- man/Makefile
- man/shairport-sync.1.xml
- shairport.c
Various minor fixes – same changes as in the previous patch but retargeted to the development branch
> Various minor fixes

- docker/Dockerfile
- docker/docker-compose.yaml
Working on top of #1642 I really needed a pipewire way of running this on my server
Thankfully adding it was not hard
One more thing I would do is move docker-compose.yaml to docker-compose.example.yaml, since most users would need to modify the file to fit their needs
> ci: build docker with pipewire

- rtp.c
I did switch to the development branch and it works for me.
I would suggest it maybe nice to check the error code and exit cleanly for #1894
And do you have a way to keep the issue in a fixed in the next release state?
So it is easier to see the issue for other people until the next release is put out.
> Check swr_init() error code and exit early.

- player.c
We discussed the possibility of sending mute state via MQTT a while ago here https://github.com/mikebrady/shairport-sync/discussions/1646
It seems the path of least resistance is to emit the same volume messages with the special muted volume value of `-144.0`.
This is in order to support implementing mute support in a Home Assistant custom integration: https://github.com/parautenbach/hass-shairport-sync/pull/14
Leaving as a draft as I have yet to fully test.
> Send pvol metadata on mute

- MQTT.md
•	Added a new section to the documentation showcasing how to use MQTTThing with Homebridge to represent Shairport-Sync’s ‘active’ status.
•	Included a practical example using the contactSensor characteristic to trigger HomeKit automations.
•	Provided clear JSON configuration for easy implementation, including topics, on/off values, and authentication details.
This addition aims to help users integrate Shairport-Sync with Homebridge using MQTTThing.
> Add Homebridge MQTTThing example to MQTT.md

- CONFIGURATION FLAGS.md
- shairport.c
A couple more typos of "daemon" (currently: "deamon").
> Fix "daemon" typos

- docker/Dockerfile
- docker/classic/Dockerfile
- docker/classic/run.sh
- docker/docker-compose.yaml
- docker/run.sh
ENABLE_AVAHI decides whether dbus and avahi daemons run inside the container or if the host's instances are reused. When set to 0, /var/run/dbus and /var/run/avahi-daemon/socket must be bind-mounted by the user from the host into the container.
Corrected version of pull request #2067
> Add ENABLE_AVAHI env var to control dbus/avahi usage in container
